### ISSUE TITLE
TypeError - no implicit conversion of Array into String

### ISSUE THREAD

**Issue by BricePissard** [CocoaPods/guides.cocoapods.org#155]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b2d641f06d538155c9eb68ab81b9024bf83633ce
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'Robby' do
  pod 'AppCenter/Core'
  pod 'AppCenter/Analytics'
  pod 'AppCenterReactNativeShared'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Stripe'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
      if target.name == "yoga"
          target.remove_from_project
      end
      if target.name == "react-native-google-maps"
        target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
      end
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['GCC_PRECOMPILE_PREFIX_HEADER'] = 'NO'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'NO'
      end
    end
  end
end
```

### Error

```
TypeError - no implicit conversion of Array into String
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:118:in `gsub'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:118:in `expand_build_setting'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:97:in `block in resolve_build_setting'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:96:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:96:in `reduce'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:96:in `resolve_build_setting'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:60:in `debug?'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:68:in `type'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:227:in `block in configuration_list'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:222:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:222:in `configuration_list'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:51:in `new_target'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project.rb:686:in `new_target'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:48:in `add_target'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:20:in `block in install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:170:in `block (2 levels) in install_libraries'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:168:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:168:in `block in install_libraries'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+Array+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Traceback (most recent call last):
	14: from /usr/local/bin/pod:23:in `<main>'
	13: from /usr/local/bin/pod:23:in `load'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:67:in `report_error'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.0/lib/gh_inspector/inspector.rb:59:in `search_exception'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.0/lib/gh_inspector/inspector.rb:65:in `search_query'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.0/lib/gh_inspector/sidekick.rb:20:in `search'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.0/lib/gh_inspector/sidekick.rb:90:in `validate_delegate'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.0/lib/gh_inspector/sidekick.rb:90:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.0/lib/gh_inspector/sidekick.rb:91:in `block in validate_delegate': #<Pod::UserInterface::InspectorReporter:0x00007ff6d7e6a2a0> does not handle inspector_successfully_received_report (RuntimeError)

**Comment by orta** [comment]
Hi, this isn't an issue with the guides website, so I'm closing it.
